#!/bin/bash

#source /opt/petalinux/2018.2/environment-setup-cortexa9hf-neon-xilinx-linux-gnueabi
mkdir -p Debug
mkdir -p Release
cd Debug
cmake -DCMAKE_BUILD_TYPE=Debug ..
cd ../Release
cmake -DCMAKE_BUILD_TYPE=Release ..

