#!/bin/bash

cd ${CLIENT_PROJECT_ROOT}/src/
gcc -c -Wall -Werror -fpic client.c
gcc -shared -o libclient.so client.o
#LD_LIBRARY_PATH=${}:$LD_LIBRARY_PATH
gcc -L${LD_LIBRARY_PATH} -Wall -o client main.c fsm.c packet.c -lclient
cp client ${CLIENT_PROJECT_ROOT}/client

cd - &> /dev/null
