#!/bin/bash

cd ${CLIENT_PROJECT_ROOT}/src/

gcc -c -Wall -Werror -fpic client.c
gcc -shared -o libclient.so client.o

export LD_LIBRARY_PATH=${CLIENT_PROJECT_ROOT}/src/
gcc -L${LD_LIBRARY_PATH} -Wall -o client main.c fsm.c packet.c -lclient

mv client ${CLIENT_PROJECT_ROOT}

cd - &> /dev/null
